import { CreateThemeOptions } from '@uiw/codemirror-themes';
declare const defaultSettingsXcodeLight: CreateThemeOptions['settings'];
declare const xcodeLightStyle: CreateThemeOptions['styles'];
declare function xcodeLightInit(options?: Partial<CreateThemeOptions>): import("@codemirror/state").Extension;
declare const xcodeLight: import("@codemirror/state").Extension[];
declare const defaultSettingsXcodeDark: CreateThemeOptions['settings'];
declare const xcodeDarkStyle: CreateThemeOptions['styles'];
declare const xcodeDarkInit: (options?: Partial<CreateThemeOptions>) => import("@codemirror/state").Extension;
declare const xcodeDark: import("@codemirror/state").Extension[];
export { defaultSettingsXcodeLight, xcodeLightStyle, xcodeLightInit, xcodeLight, defaultSettingsXcodeDark, xcodeDarkStyle, xcodeDarkInit, xcodeDark };
