const xsampa_to_ipa_code_map: Record<string, number> = {
  "b_<" : 595, // voiced bilabial implosive [ɓ]
  "d_<" : 599, // voiced alveolar implosive [ɗ]
  "d`" : 598, // voiced retroflex plosive [ɖ]
  "g_<" : 608, // voiced velar implosive [ɠ]
  "h\\" : 614, // voiced glottal fricative [ɦ]
  "j\\" : 669, // voiced palatal fricative [ʝ]
  "l\\" : 634, // alveolar lateral flap [ɺ]
  "l`" : 621, // retroflex lateral approximant [ɭ]
  "n`" : 627, // retroflex nasal [ɳ]
  "p\\" : 632, // voiceless bilabial fricative [ɸ]
  "r\\" : 633, // alveolar approximant [ɹ]
  "r\\`" : 635, // retroflex approximant [ɻ]
  "r`" : 637, // retroflex flap [ɽ]
  "s\\" : 597, // voiceless alveolo-palatal fricative [ɕ]
  "s`" : 642, // voiceless retroflex fricative [ʂ]
  "t`" : 648, // voiceless retroflex plosive [ʈ]
  "x\\" : 615, // voiceless palatal-velar fricative [ɧ]
  "z\\" : 657, // voiced alveolo-palatal fricative [ʑ]
  "z`" : 656, // voiced retroflex fricative [ʐ]
  "A" : 593, // open back unrounded vowel [ɑ]
  "B" : 946, // voiced bilabial fricative [β]
  "B\\" : 665, // bilabial trill [ʙ]
  "C" : 231, // voiceless palatal fricative [ç]
  "D" : 240, // voiced dental fricative [ð]
  "E" : 603, // open-mid front unrounded vowel [ɛ]
  "F" : 625, // labiodental nasal [ɱ]
  "G" : 611, // voiced velar fricative [ɣ]
  "G\\" : 610, // voiced uvular plosive [ɢ]
  "G\\_<" : 667, // voiced uvular implosive [ʛ]
  "H" : 613, // labial-palatal approximant [ɥ]
  "H\\" : 668, // voiceless epiglottal fricative [ʜ]
  "I" : 618, // near-close front unrounded vowel [ɪ]
  "J" : 626, // palatal nasal [ɲ]
  "J\\" : 607, // voiced palatal plosive [ɟ]
  "J\\_<" : 644, // voiced palatal implosive [ʄ]
  "K" : 620, // voiceless alveolar lateral fricative [ɬ]
  "K\\" : 622, // voiced alveolar lateral fricative [ɮ]
  "L" : 654, // palatal lateral approximant [ʎ]
  "L\\" : 671, // velar lateral approximant [ʟ]
  "M" : 623, // close back unrounded vowel [ɯ]
  "M\\" : 624, // velar approximant [ɰ]
  "N" : 331, // velar nasal [ŋ]
  "N\\" : 628, // uvular nasal [ɴ]
  "O" : 596, // open-mid back rounded vowel [ɔ]
  "O\\" : 664, // bilabial click [ʘ]
  "v\\" : 651, // labiodental approximant [ʋ]
  "P" : 651, // labiodental approximant [ʋ]
  "Q" : 594, // open back rounded vowel [ɒ]
  "R" : 641, // voiced uvular fricative [ʁ]
  "R\\" : 640, // uvular trill [ʀ]
  "S" : 643, // voiceless postalveolar fricative [ʃ]
  "T" : 952, // voiceless dental fricative [θ]
  "U" : 650, // near-close back rounded vowel [ʊ]
  "V" : 652, // open-mid back unrounded vowel [ʌ]
  "W" : 653, // voiceless labial-velar fricative [ʍ]
  "X" : 967, // voiceless uvular fricative [χ]
  "X\\" : 295, // voiceless pharyngeal fricative [ħ]
  "Y" : 655, // near-close front rounded vowel [ʏ]
  "Z" : 658, // voiced postalveolar fricative [ʒ]
  "\"" : 712, // primary stress [ˈ◌]
  "%" : 716, // secondary stress [ˌ◌]
  ":" : 720, // long [◌ː]
  ":\\" : 721, // half long [◌ˑ]
  "@" : 601, // schwa [ə]
  "@\\" : 600, // close-mid central unrounded vowel [ɘ]
  "@`" : 602, // r-coloured schwa [ɚ]
  "{" : 230, // near-open front unrounded vowel [æ]
  "}" : 649, // close central rounded vowel [ʉ]
  "1" : 616, // close central unrounded vowel [ɨ]
  "2" : 248, // close-mid front rounded vowel [ø]
  "3" : 604, // open-mid central unrounded vowel [ɜ]
  "3\\" : 606, // open-mid central rounded vowel [ɞ]
  "4" : 638, // alveolar flap [ɾ]
  "5" : 619, // velarized alveolar lateral approximant [ɫ]
  "6" : 592, // near-open central vowel [ɐ]
  "7" : 612, // close-mid back unrounded vowel [ɤ]
  "8" : 629, // close-mid central rounded vowel [ɵ]
  "9" : 339, // open-mid front rounded vowel [œ]
  "&" : 630, // open front rounded vowel [ɶ]
  "?" : 660, // glottal stop [ʔ]
  "?\\" : 661, // voiced pharyngeal fricative [ʕ]
  "<\\" : 674, // voiced epiglottal fricative [ʢ]
  ">\\" : 673, // epiglottal plosive [ʡ]
  "^" : 42779, // upstep [ꜛ]
  "!" : 42780, // downstep [ꜜ]
  "!\\" : 451, // (post)alveolar click [ǃ]
  "|" : 124, // minor (foot) group [|]
  "|\\" : 448, // dental click [ǀ]
  "||" : 8214, // major (intonation) group [‖]
  "|\\|\\" : 449, // alveolar lateral click [ǁ]
  "=\\" : 450, // palatal click [ǂ]
  "-\\" : 8255, // linking mark [‿]
  "_\"" : 776, // centralized [◌̈]
  "_+" : 799, // advanced [◌̟]
  "_-" : 800, // retracted [◌̠]
  "_0" : 805, // voiceless [◌̥]
  "_>" : 700, // ejective [◌ʼ]
  "_?\\" : 740, // pharyngealized [◌ˤ]
  "_^" : 815, // non-syllabic [◌̯]
  "_}" : 794, // no audible release [◌̚]
  "`" : 734, // retroflexion & rhoticity [◌˞]
  "=" : 809, // syllabic [◌̩]
  "_=" : 809, // syllabic [◌̩]
  "~" : 771, // anasalized [◌̃]
  "_~)" : 771, // anasalized [◌̃]
  "_A" : 792, // advanced tongue root [◌̘]
  "_a" : 826, // apical [◌̺]
  "_B" : 783, // extra low tone [◌̏]
  "_B_L" : 7622, // low rising tone [◌᷆]
  "_c" : 796, // less rounded [◌̜]
  "_d" : 810, // dental [◌̪]
  "_e" : 820, // velarized or pharyngealized; also see 5 [◌̴]
  "<F>" : 8600, // global fall [↘︎]
  "_G" : 736, // velarized [◌ˠ]
  "_H" : 769, // high tone [◌́]
  "_H_T" : 7620, // high rising tone [◌᷄]
  "_h" : 688, // aspirated [◌ʰ]
  "_j" : 690, // palatalized [◌ʲ]
  "'" : 690, // palatalized [◌ʲ]
  "_k" : 816, // creaky voice [◌̰]
  "_L" : 768, // low tone [◌̀]
  "_l" : 737, // lateral release [◌ˡ]
  "_M" : 772, // mid tone [◌̄]
  "_m" : 827, // laminal [◌̻]
  "_N" : 828, // linguolabial [◌̼]
  "_n" : 8319, // nasal release [◌ⁿ]
  "_O" : 825, // more rounded [◌̹]
  "_o" : 798, // lowered [◌̞]
  "_q" : 793, // retracted tongue root [◌̙]
  "<R>" : 8599, // global rise [↗︎]
  "_R_F" : 7624, // rising-falling tone [◌᷈]
  "_r" : 797, // raised [◌̝]
  "_T" : 779, // extra high tone [◌̋]
  "_t" : 804, // breathy voice [◌̤]
  "_v" : 812, // voiced [◌̬]
  "_w" : 695, // labialized [◌ʷ]
  "_X" : 774, // extra-short [◌̆]
  "_x" : 829, // mid-centralized [◌̽]
  "_F" : 770, // falling tone [◌̂]
  "_\\" : 770, // falling tone [◌̂]
  "_R" : 780, // rising tone [◌̌]
  "_/" : 780, // rising tone [◌̌]
  "b\\" : 11377, // voiced labiodental flap [ⱱ]
  "!\\!\\" : 8252, // retroflex click "ad hoc digraph" [‼︎]
  "_f" : 846, // whistled [◌͎]
  "_i" : 8595, // ingressive [◌↓]
  "_s" : 845, // spread lips [◌͍]
  "_u" : 840, // tenseness [◌͈]
  "_W" : 841, // weak articulation [◌͉]
  "_z" : 842, // denasalisation [◌͊]
}

const ipa_code_map_to_xsampa: Record<number, string> = {
  595 : "b_<", // voiced bilabial implosive [ɓ]
  599 : "d_<", // voiced alveolar implosive [ɗ]
  598 : "d`", // voiced retroflex plosive [ɖ]
  608 : "g_<", // voiced velar implosive [ɠ]
  614 : "h\\", // voiced glottal fricative [ɦ]
  669 : "j\\", // voiced palatal fricative [ʝ]
  634 : "l\\", // alveolar lateral flap [ɺ]
  621 : "l`", // retroflex lateral approximant [ɭ]
  627 : "n`", // retroflex nasal [ɳ]
  632 : "p\\", // voiceless bilabial fricative [ɸ]
  633 : "r\\", // alveolar approximant [ɹ]
  635 : "r\\`", // retroflex approximant [ɻ]
  637 : "r`", // retroflex flap [ɽ]
  597 : "s\\", // voiceless alveolo-palatal fricative [ɕ]
  642 : "s`", // voiceless retroflex fricative [ʂ]
  648 : "t`", // voiceless retroflex plosive [ʈ]
  615 : "x\\", // voiceless palatal-velar fricative [ɧ]
  657 : "z\\", // voiced alveolo-palatal fricative [ʑ]
  656 : "z`", // voiced retroflex fricative [ʐ]
  593 : "A", // open back unrounded vowel [ɑ]
  946 : "B", // voiced bilabial fricative [β]
  665 : "B\\", // bilabial trill [ʙ]
  231 : "C", // voiceless palatal fricative [ç]
  240 : "D", // voiced dental fricative [ð]
  603 : "E", // open-mid front unrounded vowel [ɛ]
  625 : "F", // labiodental nasal [ɱ]
  611 : "G", // voiced velar fricative [ɣ]
  610 : "G\\", // voiced uvular plosive [ɢ]
  667 : "G\\_<", // voiced uvular implosive [ʛ]
  613 : "H", // labial-palatal approximant [ɥ]
  668 : "H\\", // voiceless epiglottal fricative [ʜ]
  618 : "I", // near-close front unrounded vowel [ɪ]
  626 : "J", // palatal nasal [ɲ]
  607 : "J\\", // voiced palatal plosive [ɟ]
  644 : "J\\_<", // voiced palatal implosive [ʄ]
  620 : "K", // voiceless alveolar lateral fricative [ɬ]
  622 : "K\\", // voiced alveolar lateral fricative [ɮ]
  654 : "L", // palatal lateral approximant [ʎ]
  671 : "L\\", // velar lateral approximant [ʟ]
  623 : "M", // close back unrounded vowel [ɯ]
  624 : "M\\", // velar approximant [ɰ]
  331 : "N", // velar nasal [ŋ]
  628 : "N\\", // uvular nasal [ɴ]
  596 : "O", // open-mid back rounded vowel [ɔ]
  664 : "O\\", // bilabial click [ʘ]
  651 : "v\\", // labiodental approximant [ʋ]
  594 : "Q", // open back rounded vowel [ɒ]
  641 : "R", // voiced uvular fricative [ʁ]
  640 : "R\\", // uvular trill [ʀ]
  643 : "S", // voiceless postalveolar fricative [ʃ]
  952 : "T", // voiceless dental fricative [θ]
  650 : "U", // near-close back rounded vowel [ʊ]
  652 : "V", // open-mid back unrounded vowel [ʌ]
  653 : "W", // voiceless labial-velar fricative [ʍ]
  967 : "X", // voiceless uvular fricative [χ]
  295 : "X\\", // voiceless pharyngeal fricative [ħ]
  655 : "Y", // near-close front rounded vowel [ʏ]
  658 : "Z", // voiced postalveolar fricative [ʒ]
  712 : "\"", // primary stress [ˈ◌]
  716 : "%", // secondary stress [ˌ◌]
  720 : ":", // long [◌ː]
  721 : ":\\", // half long [◌ˑ]
  601 : "@", // schwa [ə]
  600 : "@\\", // close-mid central unrounded vowel [ɘ]
  602 : "@`", // r-coloured schwa [ɚ]
  230 : "{", // near-open front unrounded vowel [æ]
  649 : "}", // close central rounded vowel [ʉ]
  616 : "1", // close central unrounded vowel [ɨ]
  248 : "2", // close-mid front rounded vowel [ø]
  604 : "3", // open-mid central unrounded vowel [ɜ]
  606 : "3\\", // open-mid central rounded vowel [ɞ]
  638 : "4", // alveolar flap [ɾ]
  619 : "5", // velarized alveolar lateral approximant [ɫ]
  592 : "6", // near-open central vowel [ɐ]
  612 : "7", // close-mid back unrounded vowel [ɤ]
  629 : "8", // close-mid central rounded vowel [ɵ]
  339 : "9", // open-mid front rounded vowel [œ]
  630 : "&", // open front rounded vowel [ɶ]
  660 : "?", // glottal stop [ʔ]
  661 : "?\\", // voiced pharyngeal fricative [ʕ]
  674 : "<\\", // voiced epiglottal fricative [ʢ]
  673 : ">\\", // epiglottal plosive [ʡ]
  42779 : "^", // upstep [ꜛ]
  42780 : "!", // downstep [ꜜ]
  451 : "!\\", // (post)alveolar click [ǃ]
  124 : "|", // minor (foot) group [|]
  448 : "|\\", // dental click [ǀ]
  8214 : "||", // major (intonation) group [‖]
  449 : "|\\|\\", // alveolar lateral click [ǁ]
  450 : "=\\", // palatal click [ǂ]
  8255 : "-\\", // linking mark [‿]
  776 : "_\"", // centralized [◌̈]
  799 : "_+", // advanced [◌̟]
  800 : "_-", // retracted [◌̠]
  805 : "_0", // voiceless [◌̥]
  700 : "_>", // ejective [◌ʼ]
  740 : "_?\\", // pharyngealized [◌ˤ]
  815 : "_^", // non-syllabic [◌̯]
  794 : "_}", // no audible release [◌̚]
  734 : "`", // retroflexion & rhoticity [◌˞]
  809 : "=", // syllabic [◌̩]
  771 : "~", // anasalized [◌̃]
  792 : "_A", // advanced tongue root [◌̘]
  826 : "_a", // apical [◌̺]
  783 : "_B", // extra low tone [◌̏]
  7622 : "_B_L", // low rising tone [◌᷆]
  796 : "_c", // less rounded [◌̜]
  810 : "_d", // dental [◌̪]
  820 : "_e", // velarized or pharyngealized; also see 5 [◌̴]
  8600 : "<F>", // global fall [↘︎]
  736 : "_G", // velarized [◌ˠ]
  769 : "_H", // high tone [◌́]
  7620 : "_H_T", // high rising tone [◌᷄]
  688 : "_h", // aspirated [◌ʰ]
  690 : "_j", // palatalized [◌ʲ]
  816 : "_k", // creaky voice [◌̰]
  768 : "_L", // low tone [◌̀]
  737 : "_l", // lateral release [◌ˡ]
  772 : "_M", // mid tone [◌̄]
  827 : "_m", // laminal [◌̻]
  828 : "_N", // linguolabial [◌̼]
  8319 : "_n", // nasal release [◌ⁿ]
  825 : "_O", // more rounded [◌̹]
  798 : "_o", // lowered [◌̞]
  793 : "_q", // retracted tongue root [◌̙]
  8599 : "<R>", // global rise [↗︎]
  7624 : "_R_F", // rising-falling tone [◌᷈]
  797 : "_r", // raised [◌̝]
  779 : "_T", // extra high tone [◌̋]
  804 : "_t", // breathy voice [◌̤]
  812 : "_v", // voiced [◌̬]
  695 : "_w", // labialized [◌ʷ]
  774 : "_X", // extra-short [◌̆]"_w"
  829 : "_x", // mid-centralized [◌̽]
  770 : "_F", // falling tone [◌̂]
  780 : "_R", // rising tone [◌̌]
  11377 : "b\\", // voiced labiodental flap [ⱱ]
  8252 : "!\\!\\", // retroflex click "ad hoc digraph" [‼︎]
  846 : "_f", // whistled [◌͎]
  8595 : "_i", // ingressive [◌↓]
  845 : "_s", // spread lips [◌͍]
  840 : "_u", // tenseness [◌͈]
  841 : "_W", // weak articulation [◌͉]
  842 : "_z", // denasalisation [◌͊]
}

function xsampa_to_ipa(input: string) {
  const tokens = Object.keys(xsampa_to_ipa_code_map).sort((a, b) => b.length - a.length);
  let result = '';
  let i = 0;

  while (i < input.length) {
    let matched = false;
    for (const token of tokens) {
      if (input.startsWith(token, i)) {
        const code = xsampa_to_ipa_code_map[token];
        result += String.fromCharCode(code);
        i += token.length;
        matched = true;
        break;
      }
    }
    if (!matched) {
      result += input[i];  // Preserve raw character
      i++;
    }
  }

  return result;
}

function ipa_to_xsampa(ipa_in: string) {
  let result = '';

  for (let i = 0; i < ipa_in.length; i++) {
    const code = ipa_in.charCodeAt(i);
    const xsampa = ipa_code_map_to_xsampa[code];
    result += xsampa !== undefined ? xsampa : ipa_in[i]; // fallback to original char
  }

  return result;
}


export { xsampa_to_ipa, ipa_to_xsampa };